# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataidea-science',
                'doc_host': 'https://dataideaorg.github.io',
                'git_url': 'https://github.com/dataideaorg/dataidea-science',
                'lib_path': 'dataidea'},
  'syms': { 'dataidea.core': {'dataidea.core.foo': ('core.html#foo', 'dataidea/core.py')},
            'dataidea.datasets': {},
            'dataidea.plots': {},
            'dataidea.preprocessing': {}}}
