# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '',
                'doc_host': 'https://science.dataidea.org',
                'git_url': 'https://github.com/dataidea/dataidea-science',
                'lib_path': 'dataidea'},
  'syms': { 'dataidea.datasets': {},
            'dataidea.models': { 'dataidea.models.loadModel': ( 'Python-Data-Analysis/Week4-ML-Intro/overview_of_machine_learning.html#loadmodel',
                                                                'dataidea/models.py'),
                                 'dataidea.models.saveModel': ( 'Python-Data-Analysis/Week4-ML-Intro/overview_of_machine_learning.html#savemodel',
                                                                'dataidea/models.py')},
            'dataidea.packages': {},
            'dataidea.statistics': { 'dataidea.statistics.cramersV': ( 'Python-Data-Analysis/Week5-Statistics/descriptive_statistics.html#cramersv',
                                                                       'dataidea/statistics.py'),
                                     'dataidea.statistics.cramersVCorrected': ( 'Python-Data-Analysis/Week5-Statistics/descriptive_statistics.html#cramersvcorrected',
                                                                                'dataidea/statistics.py')}}}
